config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :contacts

  root 'home#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email_address, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email address</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.email_address %></td>
        <td><%= contact.description %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @contact.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.last_name %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @contact.email_address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @contact.description %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/home/index.html.erb
<h1>Contacts</h1>

<form id="addContact" class="module">
  <div>
    <label for="first_name">First Name:</label>
    <input type="text" id="first_name" name="first_name" value="">
  </div>

  <div>
    <label for="last_name">Last Name:</label>
    <input type="text" id="last_name" name="last_name" value="">
  </div>

  <div>
    <label for="email_address">Email Address:</label>
    <input type="text" id="email_address" name="email_address" value="">
  </div>

  <div>
    <label for="description">Description:</label>
    <textarea id="description" name="description"></textarea>
  </div>

  <div>
    <input type="submit" value="Add Contact">
  </div>
</form>

<table id="allContacts" class="module">
  <thead>
    <tr>
      <td>First Name</td>
      <td>Last Name</td>
      <td>Email Address</td>
      <td>Description</td>
      <td>Options</td>
    </tr>
  </thead>
</table>

<div id="editContact"></div>

<script id="allContactsTemplate" type="text/template">
  <td><%%= first_name %></td>
  <td><%%= last_name %></td>
  <td><%%= email_address %></td>
  <td><%%= description %></td>
  <td><a href="#contacts/<%%= id %>" class="delete">Delete</a></td>
  <td><a href="#contacts/<%%= id %>/edit" class="edit">Edit</a></td>
</script>

<script id="editContactTemplate" type="text/template">
  <h2>Edit Contact: <%%= first_name %> <%%= last_name %> </h2>
  <form id="editContact">
    <div>
      <label for="edit_first_name">First Name:</label>
      <input type="text" id="edit_first_name" name="edit_first_name" value="<%%= first_name %>">
    </div>

    <div>
      <label for="edit_last_name">Last Name:</label>
      <input type="text" id="edit_last_name" name="edit_last_name" value="<%%= last_name %>">
    </div>

    <div>
      <label for="edit_email_address">Email Address:</label>
      <input type="text" id="edit_email_address" name="edit_email_address" value="<%%= email_address %>">
    </div>

    <div>
      <label for="edit_description">Description:</label>
      <textarea id="edit_description" name="edit_description"  value="<%%= description %>"></textarea>
    </div>

    <div>
      <input type="submit" value="Add Contact">
      <button type="button" class="cancel">Cancel</button>
    </div>
  </form>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactsManagerBackbone</title>
  <style>
    table thead td { font-weight: bold; }
    .module { margin-bottom: 2em; }
  </style>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<script src="http://code.jquery.com/jquery.js"></script>
<script src="http://underscorejs.org/underscore.js"></script>
<script src="http://backbonejs.org/backbone.js"></script>
<%= javascript_include_tag 'application' %>

<script>
  new App.Router;
  Backbone.history.start();

  App.contacts = new App.Collections.Contacts;
  App.contacts.fetch().then(function(){
    new App.Views.App({ collection: App.contacts });
  });
</script>
</body>
</html>